"""STAR Chemistry canonical topics 476-500 of 500."""

CHEMISTRY_ROWS_20 = r"""\
radioactive_decay_chem	nuclear_ambiental_aplicada	2	Decaimento radioativo	N=N0e^-λt; A=λN	Modela transformação espontânea de radionuclídeos por lei exponencial.	decaimento radioativo;atividade;lambda	IUPAC
half_life_radio	nuclear_ambiental_aplicada	2	Meia-vida radioativa	t_1/2=ln2/λ	Relaciona constante de decaimento ao tempo para reduzir população à metade.	meia vida;radioatividade;lambda	IUPAC
decay_constant_activity	nuclear_ambiental_aplicada	2	Constante de decaimento e atividade	A=-dN/dt=λN	Define taxa de desintegração de uma população radioativa.	atividade;becquerel;constante decaimento	IUPAC
decay_chains	nuclear_ambiental_aplicada	4	Cadeias de decaimento	dN_i/dt=produção-decai por λ_i	Representa sequências de radionuclídeos acoplados por equações diferenciais.	cadeia decaimento;bateman;radionuclideo	IAEA
radiochemical_yield	nuclear_ambiental_aplicada	3	Rendimento radioquímico	Y_rad=atividade recuperada/atividade inicial corrigida ×100%	Quantifica recuperação de radionuclídeo em separação química.	rendimento radioquimico;atividade recuperada;radiochemistry	IAEA
isotope_dilution	nuclear_ambiental_aplicada	4	Diluição isotópica	quantidade é inferida da razão isotópica após mistura com spike conhecido	Permite quantificação robusta por balanço isotópico.	diluicao isotopica;spike;razao isotopica	IAEA
radiometric_dating	nuclear_ambiental_aplicada	3	Datação radiométrica	t=(1/λ)ln(N0/N) em sistema simples fechado	Infere tempo a partir de decaimento e hipóteses sobre sistema e condições iniciais.	datacao radiometrica;idade;decaimento	IAEA
radiation_chemistry_g_value	nuclear_ambiental_aplicada	4	Rendimento G em química da radiação	G=eventos químicos por energia absorvida, em convenção definida	Quantifica produtos ou transformações induzidas por radiação ionizante.	g value;quimica radiacao;rendimento	IUPAC
radiolysis_water	nuclear_ambiental_aplicada	4	Radiólise da água	H2O --radiação→ e_aq^-, ·OH, ·H e produtos secundários	Introduz espécies reativas geradas por radiação em meio aquoso.	radiolise;agua;radical hidroxila	IUPAC
partition_coefficient_environment	nuclear_ambiental_aplicada	3	Coeficiente de partição ambiental	K_ow=C_octanol/C_água	Indica tendência de uma espécie neutra distribuir-se entre fase orgânica e água.	kow;octanol agua;particao ambiental	PUBCHEM
logp_logd	nuclear_ambiental_aplicada	3	logP e logD	logP=log10 K_ow para forma neutra; logD depende de pH para espécies ionizáveis	Distingue hidrofobicidade intrínseca de distribuição dependente de especiação.	logp;logd;lipofilia;ph	PUBCHEM
henry_environment	nuclear_ambiental_aplicada	3	Constante de Henry ambiental	H relaciona fugacidade/pressão gasosa à concentração dissolvida conforme convenção	Ajuda a avaliar partição ar–água de compostos voláteis.	henry ambiental;volatilidade;ar agua	IUPAC
acid_rain_equilibria	nuclear_ambiental_aplicada	2	Equilíbrios químicos de chuva ácida	SOx/NOx podem formar ácidos e alterar [H+] em água atmosférica	Conecta oxidação atmosférica e ácido–base sem reduzir o fenômeno a uma única reação.	chuva acida;sox;nox;ph	OPENSTAX
carbonate_system	nuclear_ambiental_aplicada	3	Sistema carbonato em água	CO2(aq)⇌H2CO3*⇌HCO3-⇌CO3^2-	Controla alcalinidade, tamponamento e especiação inorgânica de carbono.	sistema carbonato;bicarbonato;alcalinidade	OPENSTAX
alkalinity	nuclear_ambiental_aplicada	3	Alcalinidade	Alk≈[HCO3-]+2[CO3^2-]+[OH-]-[H+] + outras bases	Mede capacidade ácido-neutralizante total com convenção de espécies.	alcalinidade;agua;carbonato	LIBRE_ANALYTICAL
redox_pe_eh	nuclear_ambiental_aplicada	4	pe, Eh e especiação redox	Eh=(2.303RT/F)pe sob convenção eletrônica	Relaciona atividade eletrônica formal e potencial redox ambiental.	pe;eh;especiacao redox	IUPAC
chemical_oxygen_demand_concept	nuclear_ambiental_aplicada	3	Demanda química de oxigênio	DQO expressa equivalente oxidável sob método definido	Serve como indicador agregado de matéria oxidável, dependente do protocolo analítico.	dqo;cod;materia organica	LIBRE_ANALYTICAL
atmospheric_steady_state	nuclear_ambiental_aplicada	4	Estado estacionário em química atmosférica	d[X]/dt=P_X-L_X≈0	Estima concentrações quando produção e perda se equilibram rapidamente.	estado estacionario;atmosfera;producao perda	MIT_560
photolysis_rate	nuclear_ambiental_aplicada	4	Taxa de fotólise	J=∫σ(λ)Φ(λ)F(λ)dλ em forma geral	Relaciona fluxo espectral, seção de choque e rendimento quântico à fotodissociação.	fotolise;j value;secao choque	IUPAC
green_chemistry_mass_intensity	nuclear_ambiental_aplicada	3	Intensidade de massa de processo	PMI=massa total de entradas/massa de produto	Quantifica uso material global de um processo químico.	pmi;quimica verde;intensidade massa	IUPAC
e_factor	nuclear_ambiental_aplicada	3	E-factor	E=m_resíduo/m_produto	Quantifica geração de resíduos por massa de produto em fronteira definida.	e factor;residuo;quimica verde	IUPAC
reaction_mass_efficiency	nuclear_ambiental_aplicada	3	Eficiência de massa da reação	RME=100 m_produto/(Σm_reagentes usados)	Combina estequiometria e rendimento em métrica de eficiência material.	rme;eficiencia massa;quimica verde	IUPAC
life_cycle_chemistry_concept	nuclear_ambiental_aplicada	4	Pensamento de ciclo de vida em química	impacto total = soma de etapas e fluxos dentro da fronteira definida	Evita otimizar uma etapa transferindo impacto para outra.	ciclo de vida;lca;quimica sustentavel	IUPAC
uncertainty_model_validation	nuclear_ambiental_aplicada	5	Validação de modelos químicos	resíduos, sensibilidade e validação externa testam adequação do modelo	Distingue ajuste numérico de capacidade preditiva e domínio de aplicabilidade.	validacao modelo;residuo;sensibilidade;dominio aplicabilidade	NIST_CCCBDB
multiscale_chemistry	nuclear_ambiental_aplicada	5	Química multiescala	eletrônico→molecular→mesoscópico→macroscópico	Integra métodos quânticos, dinâmica molecular, cinética e termodinâmica por escalas.	multiescala;quimica computacional;modelagem	NIST_CCCBDB
"""
