"""STAR Chemistry canonical topics 326-350 of 500."""

CHEMISTRY_ROWS_14 = r"""\
sn2	organica_reacoes_sintese	2	Substituição nucleofílica SN2	v=k[RX][Nu-]	Mecanismo concertado com inversão de configuração e forte dependência estérica.	sn2;substituicao nucleofilica;bimolecular	MIT_ORG
sn1	organica_reacoes_sintese	2	Substituição nucleofílica SN1	v=k[RX]	Mecanismo ionizante em etapas via carbocátion em casos adequados.	sn1;carbocation;substituicao unimolecular	MIT_ORG
e2	organica_reacoes_sintese	2	Eliminação E2	v=k[RX][Base]	Eliminação concertada favorecida por geometria antiperiplanar.	e2;eliminacao;bimolecular	MIT_ORG
e1	organica_reacoes_sintese	2	Eliminação E1	v=k[RX]	Eliminação em etapas via carbocátion que compete com SN1.	e1;eliminacao;carbocation	MIT_ORG
substitution_elimination_competition	organica_reacoes_sintese	3	Competição substituição–eliminação	produto depende de substrato, nucleófilo/base, solvente e temperatura	Integra fatores que direcionam SN1/SN2/E1/E2.	sn1 sn2 e1 e2;competicao;substrato	MIT_ORG
alkene_electrophilic_addition	organica_reacoes_sintese	2	Adição eletrofílica a alcenos	π + E+ → intermediário → produto	Explica consumo da ligação π por eletrófilos e nucleófilos.	adicao alceno;adicao eletrofilica;markovnikov	MIT_ORG
markovnikov_regioselectivity	organica_reacoes_sintese	2	Regiosseletividade de Markovnikov	orientação segue estabilidade eletrônica do caminho, não uma força isolada	Prevê orientação comum em certas adições a alcenos assimétricos.	markovnikov;regiosseletividade;alceno	MIT_ORG
alkyne_reactivity	organica_reacoes_sintese	2	Reatividade de alcinos	duas ligações π permitem sequências de adição	Relaciona hibridização sp, acidez terminal e reações de adição.	alcino;tripla ligacao;acetileno	MIT_ORG
alcohol_reactivity	organica_reacoes_sintese	2	Química de álcoois	ROH pode atuar como ácido/base fraco, nucleófilo ou precursor de grupo de saída	Organiza oxidação, substituição, eliminação e formação de derivados em nível conceitual.	alcool;roh;oxidacao alcool	MIT_ORG
ether_epoxide	organica_reacoes_sintese	3	Éteres e epóxidos	tensão de epóxido aumenta suscetibilidade à abertura nucleofílica	Compara estabilidade de éteres e reatividade de anéis de três membros.	eter;epoxido;abertura anel	MIT_ORG
carbonyl_nucleophilic_addition	organica_reacoes_sintese	3	Adição nucleofílica a carbonila	Nu adiciona ao C eletrofílico de C=O	Base mecanística para aldeídos e cetonas.	carbonila;adicao nucleofilica;aldeido cetona	MIT_ORG
nucleophilic_acyl_substitution	organica_reacoes_sintese	3	Substituição nucleofílica acílica	adição → intermediário tetraédrico → eliminação	Organiza interconversões entre derivados de ácido carboxílico.	substituicao acilica;derivados acido;intermediario tetraedrico	MIT_ORG
carboxylic_acid_derivatives	organica_reacoes_sintese	2	Derivados de ácidos carboxílicos	reatividade depende de capacidade do grupo de saída e ressonância	Compara haletos de acila, anidridos, ésteres e amidas conceitualmente.	derivados acido carboxilico;ester;amida	MIT_ORG
enol_enolate	organica_reacoes_sintese	3	Enóis e enolatos	carbonila⇌enol; desprotonação α gera enolato	Conecta tautomeria e nucleofilia no carbono alfa.	enol;enolato;tautomeria	MIT_ORG
aldol_reaction	organica_reacoes_sintese	3	Reação aldólica	enolato/enol + carbonila → β-hidroxicarbonila	Forma ligação C–C por química de carbonilas enolizáveis.	aldol;ligacao c c;enolato	MIT_ORG
claisen_condensation	organica_reacoes_sintese	4	Condensação de Claisen	enolato de éster + éster → β-dicarbonila sob condições compatíveis	Exemplifica substituição acílica acoplada a formação C–C.	claisen;ester;beta dicarbonila	MIT_ADV_ORG
aromatic_electrophilic_substitution	organica_reacoes_sintese	3	Substituição eletrofílica aromática	Ar-H + E+ → Ar-E + H+ via intermediário σ	Mantém aromaticidade global após substituição.	substituicao aromatica eletrofilica;sea;anel aromatico	MIT_ORG
directing_effects_aromatic	organica_reacoes_sintese	3	Efeitos diretores em aromáticos	substituintes alteram densidade e estabilidade de intermediários orto/meta/para	Explica regioseletividade por ressonância e indução.	diretor orto para;diretor meta;aromatico	MIT_ORG
nucleophilic_aromatic_substitution	organica_reacoes_sintese	4	Substituição nucleofílica aromática	mecanismo depende de ativação e grupo de saída; vias não são universais	Distingue mecanismos aromáticos nucleofílicos de SN1/SN2 alifáticos.	sna;substituicao nucleofilica aromatica;meisenheimer	MIT_ADV_ORG
diels_alder	organica_reacoes_sintese	4	Cicloadição de Diels–Alder	4π+2π→anel de seis membros	Reação pericíclica concertada com controle estereoquímico e orbital.	diels alder;cicloadicao;periciclica	MIT_ADV_ORG
radical_chain_reactions	organica_reacoes_sintese	3	Reações radicalares em cadeia	iniciação→propagação→terminação	Organiza mecanismos sustentados por portadores radicalares.	reacao radicalar;cadeia;propagacao	MIT_ADV_ORG
photochemical_reactions	organica_reacoes_sintese	4	Reações fotoquímicas	absorção hν cria estado excitado com superfície reativa distinta	Distingue química do estado excitado de vias térmicas.	fotoquimica;estado excitado;hv	IUPAC
retrosynthesis	organica_reacoes_sintese	4	Retrossíntese	alvo→desconexões→synthons/equivalentes	Planeja rotas por análise reversa de ligações e compatibilidade funcional, sem prescrever procedimento operacional.	retrossintese;desconexao;planejamento sintese	MIT_ADV_ORG
chemoselectivity_regio_stereo	organica_reacoes_sintese	4	Quimiosseletividade, regiosseletividade e estereosseletividade	seleção de função, posição e estereoisômero são eixos independentes	Avalia resultado de transformações por três dimensões de seletividade.	quimiosseletividade;regiosseletividade;estereosseletividade	IUPAC
green_synthesis_metrics	organica_reacoes_sintese	4	Métricas de síntese verde	PMI=massa total de entradas/massa de produto; E-factor=m_resíduos/m_produto	Avalia eficiência material de rotas sem implicar uma receita específica.	pmi;e factor;quimica verde;sintese	IUPAC
"""
