"""STAR Chemistry canonical topics 376-400 of 500."""

CHEMISTRY_ROWS_16 = r"""\
metal_carbon_bond	organometalica_catalise	3	Ligação metal–carbono	descrição varia entre σ, π e interações multicêntricas	Define núcleo estrutural da química organometálica.	metal carbono;organometalico;ligacao m c	MIT_ADV_ORG
electron_counting_18e	organometalica_catalise	3	Contagem eletrônica e regra dos 18 elétrons	VE_total=elétrons do metal + doações dos ligantes	Fornece heurística de estabilidade para muitos complexos de metais de transição.	regra 18 eletrons;contagem eletronica;complexo	MIT_INORG
hapticity	organometalica_catalise	3	Hapticidade η	η^n indica n átomos contíguos do ligante ligados ao metal	Descreve ligantes π como ciclopentadienila ou alquenos.	hapticidade;eta;ligante pi	IUPAC
metal_carbonyl_bonding	organometalica_catalise	4	Ligação em carbonilas metálicas	σ doação CO→M e π retrodoação M→CO	Explica sinergia eletrônica e mudanças espectroscópicas em M–CO.	carbonila metalica;retrodoacao;backbonding	MIT_INORG
oxidative_addition	organometalica_catalise	4	Adição oxidativa	M + A-B → A-M-B com aumento formal de NOX e coordenação	Etapa elementar organometálica que adiciona uma ligação ao centro metálico.	adicao oxidativa;oxidative addition;organometalica	IUPAC
reductive_elimination	organometalica_catalise	4	Eliminação redutiva	A-M-B → M + A-B com redução formal do metal	Etapa inversa conceitual da adição oxidativa.	eliminacao redutiva;reductive elimination	IUPAC
migratory_insertion	organometalica_catalise	4	Inserção migratória	grupo ligado ao metal migra para ligante insaturado coordenado	Explica formação de novas ligações em ciclos catalíticos.	insercao migratoria;co insertion;organometalica	IUPAC
beta_hydride_elimination	organometalica_catalise	4	Eliminação β-hidreto	M-alkyl com Hβ → M-H + alceno	Etapa frequente que compete com propagação ou funcionalização.	beta hidreto;eliminacao;metal alquil	IUPAC
ligand_substitution_organometallic	organometalica_catalise	4	Substituição de ligante em organometálicos	vias associativa, dissociativa ou intercâmbio dependem do complexo	Relaciona cinética de coordenação a saturação eletrônica e geometria.	substituicao ligante;associativa;dissociativa	MIT_INORG
trans_effect	organometalica_catalise	4	Efeito trans	certos ligantes aceleram substituição na posição trans em complexos quadrado-planares	Distingue efeito cinético trans de influência termodinâmica trans.	efeito trans;quadrado planar;substituicao	MIT_INORG
homogeneous_catalysis_cycle	organometalica_catalise	3	Ciclo catalítico homogêneo	TOF=mol produto/(mol catalisador·tempo)	Representa regeneração do catalisador por sequência fechada de etapas.	ciclo catalitico;catálise homogenea;tof	IUPAC
turnover_number	organometalica_catalise	3	Número de turnover	TON=mol produto/mol catalisador	Mede produtividade total de catalisador antes de desativação.	ton;turnover number;catalisador	IUPAC
turnover_frequency	organometalica_catalise	3	Frequência de turnover	TOF=d(TON)/dt	Mede taxa de ciclos catalíticos por sítio ativo sob definição explícita.	tof;turnover frequency;atividade catalitica	IUPAC
catalyst_selectivity	organometalica_catalise	3	Seletividade catalítica	S_i=produto_i/Σprodutos em base definida	Quantifica preferência por produto entre caminhos concorrentes.	seletividade catalitica;catalisador;produto	IUPAC
sabatier_principle	organometalica_catalise	4	Princípio de Sabatier	interação catalisador-intermediário não deve ser nem fraca nem forte demais	Explica tendências tipo vulcão em catálise heterogênea.	sabatier;volcano plot;adsorcao	IUPAC
langmuir_adsorption	organometalica_catalise	4	Isoterma de Langmuir	θ=KP/(1+KP) em adsorção ideal monocomponente	Modela ocupação de sítios equivalentes sem interação lateral.	langmuir;isoterma;adsorcao	IUPAC
langmuir_hinshelwood	organometalica_catalise	5	Mecanismo Langmuir–Hinshelwood	r depende das coberturas de duas espécies adsorvidas	Descreve reação superficial entre reagentes coadsorvidos.	langmuir hinshelwood;reacao superficie;cobertura	IUPAC
eley_rideal	organometalica_catalise	5	Mecanismo Eley–Rideal	espécie gasosa/solução reage diretamente com espécie adsorvida	Contrasta com reação entre duas espécies adsorvidas.	eley rideal;catálise heterogenea;adsorcao	IUPAC
volcano_relationships	organometalica_catalise	5	Relações vulcão em catálise	atividade máxima em energia de ligação/intermediário intermediária	Conecta descritores de adsorção a atividade catalítica.	volcano plot;descritor;atividade catalitica	IUPAC
cross_coupling_concept	organometalica_catalise	4	Acoplamento cruzado catalítico	ciclo típico combina ativação de parceiros, formação C–C/C–heteroátomo e regeneração	Organiza conceitualmente famílias de acoplamento sem prescrever procedimento experimental.	acoplamento cruzado;cross coupling;paladio	MIT_ADV_ORG
olefin_metathesis_concept	organometalica_catalise	4	Metátese de olefinas	redistribuição de fragmentos de ligações C=C via catalisador apropriado	Explica transformação de alcenos como processo de troca de parceiros.	metatese olefinas;metathesis;alceno	IUPAC
hydrogenation_catalysis	organometalica_catalise	3	Catálise de hidrogenação	velocidade e seletividade dependem de adsorção/coordenação e transferência de H	Conecta ativação de H2 e insaturações em catálise homogênea ou heterogênea.	hidrogenacao;catálise;h2	MIT_5111
photocatalysis	organometalica_catalise	4	Fotocatálise	absorção de luz cria portadores/estados excitados que alteram a taxa química	Integra fotoquímica e catálise por processos iniciados pela luz.	fotocatalise;fotocatalisador;luz	IUPAC
electrocatalysis	organometalica_catalise	5	Eletrocatálise	atividade relaciona sobrepotencial, corrente e ocupação de sítios	Descreve aceleração de reações de eletrodo por superfícies ou complexos.	eletrocatalise;sobrepotencial;catalisador	IUPAC
catalyst_deactivation	organometalica_catalise	4	Desativação catalítica	atividade(t) cai por envenenamento, sinterização, coque ou mudanças estruturais	Distingue perda reversível e irreversível de desempenho.	desativacao catalisador;envenenamento;sinterizacao	IUPAC
"""
