"""STAR Chemistry canonical topics 351-375 of 500."""

CHEMISTRY_ROWS_15 = r"""\
oxidation_state_inorganic	inorganica_coordenacao	1	Estado de oxidação em inorgânica	Σ NOX = carga total	Organiza contagem eletrônica formal em compostos moleculares e iônicos.	estado oxidacao;inorganica;nox	OPENSTAX
coordination_number	inorganica_coordenacao	2	Número de coordenação	CN = número de átomos doadores diretamente ligados ao centro	Classifica ambiente de coordenação de íons e átomos centrais.	numero coordenacao;complexo;ligante	IUPAC
ligands_denticity	inorganica_coordenacao	2	Ligantes e denticidade	denticidade = número de sítios doadores de um ligante	Distingue ligantes mono, bi e polidentados.	ligante;denticidade;quelato	OPENSTAX
coordination_nomenclature	inorganica_coordenacao	2	Nomenclatura de complexos	nome ordena ligantes, metal e estado de oxidação conforme regras	Relaciona fórmula de coordenação a nomenclatura sistemática.	nomenclatura complexo;coordenacao;iupac	IUPAC
coordination_isomerism	inorganica_coordenacao	3	Isomeria em compostos de coordenação	mesma composição pode ter conectividade ou geometria diferente	Inclui isomeria geométrica, óptica, de ligação e de coordenação.	isomeria coordenacao;cis trans;fac mer	OPENSTAX
crystal_field_oct	inorganica_coordenacao	3	Campo cristalino octaédrico	Δ_o separa t2g e eg	Modela separação dos orbitais d sob campo octaédrico.	campo cristalino;octaedrico;delta o	OPENSTAX
crystal_field_tet	inorganica_coordenacao	3	Campo cristalino tetraédrico	Δ_t≈4/9 Δ_o em comparação idealizada	Modela separação dos orbitais d em geometria tetraédrica.	campo cristalino;tetraedrico;delta t	OPENSTAX
high_low_spin	inorganica_coordenacao	3	Alto spin e baixo spin	competição entre Δ e energia de pareamento P	Determina ocupação eletrônica em complexos d sob diferentes campos.	alto spin;baixo spin;pareamento	OPENSTAX
cfse	inorganica_coordenacao	4	Energia de estabilização de campo cristalino	CFSE=Σ n_i E_i relativo ao baricentro	Quantifica estabilização eletrônica no modelo de campo cristalino.	cfse;estabilizacao campo cristalino;orbitais d	OPENSTAX
spectrochemical_series	inorganica_coordenacao	3	Série espectroquímica	ligantes ordenados por magnitude típica de Δ	Compara força de campo de ligantes empiricamente.	serie espectroquimica;ligante forte;ligante fraco	OPENSTAX
ligand_field_theory	inorganica_coordenacao	4	Teoria de campo ligante	combina simetria, orbitais do metal e ligantes em descrição MO	Refina campo cristalino incluindo covalência.	campo ligante;ligand field;orbital molecular	MIT_INORG
magnetic_moment_spin_only	inorganica_coordenacao	3	Momento magnético spin-only	μ_eff≈sqrt(n(n+2)) μ_B	Estima paramagnetismo a partir de elétrons desemparelhados.	momento magnetico;paramagnetismo;spin only	OPENSTAX
color_transition_metal	inorganica_coordenacao	3	Cor em complexos de metais de transição	absorção visível depende de Δ e transições eletrônicas	Relaciona estrutura eletrônica a cor observada.	cor complexo;transicao d d;metal transicao	OPENSTAX
tanabe_sugano_intro	inorganica_coordenacao	5	Diagramas de Tanabe–Sugano	E/B versus Δ/B	Organiza energias de termos eletrônicos em complexos de metais de transição.	tanabe sugano;termos eletronicos;espectro complexo	MIT_INORG
jahn_teller	inorganica_coordenacao	4	Efeito Jahn–Teller	degenerescência eletrônica pode dirigir distorção geométrica	Explica distorções de complexos com estados eletrônicos degenerados.	jahn teller;distorcao;degenerescencia	MIT_INORG
chelate_effect	inorganica_coordenacao	3	Efeito quelato	estabilidade frequentemente aumenta com ligantes multidentados	Relaciona entropia, pré-organização e ligações múltiplas à estabilidade de complexos.	efeito quelato;ligante polidentado;estabilidade	OPENSTAX
hsab	inorganica_coordenacao	4	Ácidos e bases duros e moles	afinidade qualitativa duro-duro e mole-mole	Organiza tendências de coordenação e reatividade de Lewis.	hsab;duro mole;pearson	IUPAC
main_group_inert_pair	inorganica_coordenacao	4	Efeito do par inerte	estados de oxidação baixos tornam-se mais estáveis em elementos pesados de certos grupos	Relaciona efeitos relativísticos e energia orbital a química do bloco p.	par inerte;bloco p;estado oxidacao	MIT_INORG
boranes_wade	inorganica_coordenacao	5	Regras de Wade para boranos	pares esqueléticos n+1,n+2,n+3 para closo,nido,arachno em modelos clássicos	Classifica estruturas de clusters deficientes em elétrons.	wade;borano;closo nido arachno	MIT_INORG
electron_deficient_bonding	inorganica_coordenacao	4	Ligação deficiente em elétrons	ligações multicêntricas distribuem pares por mais de dois centros	Descreve espécies que não cabem em ligações 2c-2e simples.	ligacao multicentrica;3c2e;deficiente eletrons	MIT_INORG
solid_state_ionic_structures	inorganica_coordenacao	3	Estruturas iônicas de sólidos	coordenação depende de tamanho, carga e empacotamento	Compara motivos como NaCl, CsCl e ZnS como modelos estruturais.	estrutura nacl;cscl;zns;solido ionico	OPENSTAX
band_structure_inorganic	inorganica_coordenacao	4	Estrutura de bandas em sólidos inorgânicos	E(k) forma bandas permitidas separadas por gaps	Conecta orbitais estendidos a comportamento metálico, semicondutor e isolante.	estrutura bandas;gap;solido	MIT_5111
defects_solids	inorganica_coordenacao	4	Defeitos em sólidos	concentração de defeitos ∝ exp(-ΔG_f/kT) em modelo diluído	Mostra impacto de vacâncias, intersticiais e substituições em propriedades.	defeito cristal;vacancia;intersticial	MIT_INORG
nonstoichiometric_solids	inorganica_coordenacao	4	Sólidos não estequiométricos	composição pode variar mantendo estrutura por defeitos compensadores	Relaciona defeitos e estados de oxidação a fórmulas não integrais.	nao estequiometrico;defeitos;oxidos	MIT_INORG
bioinorganic_metals	inorganica_coordenacao	4	Química bioinorgânica de metais	função depende de coordenação, estado redox e ambiente proteico	Conecta princípios de coordenação a cofatores metálicos biológicos.	bioinorganica;metaloproteina;cofator metal	MIT_5111
"""
