"""STAR Chemistry canonical topics 1-100 of 500."""

CHEMISTRY_ROWS_01 = r"""\
matter_classification	fundamentos_medicao	1	Classificação da matéria	substância pura ≠ mistura; fase = região homogênea	Distingue elementos, compostos, misturas homogêneas e heterogêneas.	materia;substancia pura;mistura;fase	OPENSTAX
physical_chemical_properties	fundamentos_medicao	1	Propriedades físicas e químicas	ρ=m/V	Separa propriedades observáveis sem reação das que descrevem transformação química.	propriedade fisica;propriedade quimica;densidade	OPENSTAX
si_units_chemistry	fundamentos_medicao	1	Unidades SI em química	N_A=6.02214076×10^23 mol^-1	Organiza grandezas químicas em unidades coerentes e rastreáveis.	si;unidades;mole;mol	IUPAC
significant_figures	fundamentos_medicao	1	Algarismos significativos	resultado limitado pela precisão dos dados	Controla arredondamento e comunicação da incerteza numérica.	algarismos significativos;arredondamento;precisao	OPENSTAX
scientific_notation	fundamentos_medicao	1	Notação científica e ordens de grandeza	x=a×10^n, 1≤|a|<10	Facilita cálculos químicos que atravessam muitas escalas.	notacao cientifica;ordem de grandeza;potencias de dez	OPENSTAX
dimensional_analysis_chem	fundamentos_medicao	1	Análise dimensional em química	valor×fatores de conversão	Converte unidades preservando a dimensão física e química.	analise dimensional;conversao de unidades;fator de conversao	OPENSTAX
measurement_uncertainty	fundamentos_medicao	2	Incerteza de medição	u_c≈sqrt(Σu_i^2)	Expressa quantitativamente a dispersão associada a medidas combinadas.	incerteza;erro;metrologia quimica	IUPAC
accuracy_precision	fundamentos_medicao	1	Exatidão e precisão	erro relativo=(x-x_ref)/x_ref	Diferencia proximidade ao valor de referência de repetibilidade.	exatidao;precisao;erro relativo	IUPAC
percent_error	fundamentos_medicao	1	Erro percentual	erro%=100|x-x_ref|/|x_ref|	Quantifica desvio relativo entre medida e referência.	erro percentual;desvio percentual	OPENSTAX
chemical_symbols_formulas	fundamentos_medicao	1	Símbolos e fórmulas químicas	fórmula = composição estequiométrica	Representa espécies químicas por símbolos, índices e cargas.	formula quimica;simbolo quimico;indices	IUPAC
empirical_molecular_formula	fundamentos_medicao	2	Fórmula empírica e molecular	n=M_molecular/M_empírica	Relaciona proporção mínima inteira com fórmula molecular real.	formula empirica;formula molecular;composicao	OPENSTAX
molar_mass	fundamentos_medicao	1	Massa molar	M=m/n	Relaciona massa de amostra e quantidade de matéria.	massa molar;mol;quantidade de materia	OPENSTAX
amount_of_substance	fundamentos_medicao	1	Quantidade de matéria	n=N/N_A	Conecta número de entidades ao mol.	quantidade de materia;numero de particulas;avogadro	IUPAC
avogadro_constant	fundamentos_medicao	1	Constante de Avogadro	N_A=6.02214076×10^23 mol^-1	Define a escala entre entidades microscópicas e quantidade de matéria.	avogadro;constante de avogadro;numero de entidades	IUPAC
mass_percent	fundamentos_medicao	1	Percentual em massa	%m=100 m_soluto/m_total	Expressa composição como fração mássica percentual.	percentual em massa;fracao massica;composicao percentual	OPENSTAX
ppm_ppb	fundamentos_medicao	2	ppm e ppb	ppm≈10^6 m_soluto/m_total; ppb≈10^9	Expressa concentrações muito pequenas em bases proporcionais.	ppm;ppb;tracos	IUPAC
molarity	fundamentos_medicao	1	Concentração molar	c=n/V	Relaciona quantidade de soluto ao volume de solução.	molaridade;concentracao molar;mol por litro	IUPAC
molality	fundamentos_medicao	2	Molalidade	b=n_soluto/m_solvente(kg)	Relaciona quantidade de soluto à massa do solvente, independente de expansão volumétrica.	molalidade;concentracao por massa de solvente	IUPAC
mole_fraction	fundamentos_medicao	2	Fração molar	x_i=n_i/Σn_j	Expressa composição relativa em quantidade de matéria.	fracao molar;composicao;mistura	IUPAC
normality_equivalents	fundamentos_medicao	2	Equivalentes e concentração equivalente	c_eq=n_eq/V	Relaciona quantidade de equivalentes à capacidade reativa definida pelo processo.	normalidade;equivalente;concentracao equivalente	IUPAC
density_specific_gravity	fundamentos_medicao	1	Densidade e densidade relativa	ρ=m/V; d=ρ/ρ_ref	Conecta massa, volume e comparação com uma substância de referência.	densidade;densidade relativa;gravidade especifica	OPENSTAX
temperature_scales	fundamentos_medicao	1	Escalas de temperatura	T(K)=t(°C)+273.15	Converte escalas sem confundir diferença de temperatura com temperatura absoluta.	kelvin;celsius;temperatura	IUPAC
chemical_equation_notation	fundamentos_medicao	1	Equação de reação química	Σν_i A_i=0	Representa reagentes, produtos e números estequiométricos de uma reação.	equacao quimica;reacao;coeficiente estequiometrico	IUPAC
law_conservation_mass	fundamentos_medicao	1	Conservação de massa	Σm_reagentes=Σm_produtos	Impõe balanço de átomos em sistemas fechados não nucleares.	conservacao de massa;balanco de massa;lei de lavoisier	OPENSTAX
chemical_safety_labels	fundamentos_medicao	2	Informação química e rotulagem de segurança	risco=f(perigo,exposição)	Distingue identidade, perigo intrínseco e contexto de exposição sem substituir procedimentos institucionais.	seguranca quimica;rotulo;perigo;risco	PUBCHEM
atomic_number_mass	estrutura_atomica_periodicidade	1	Número atômico e número de massa	Z=p; A=p+n	Relaciona prótons, nêutrons e identidade elementar.	numero atomico;numero de massa;protons;neutrons	OPENSTAX
isotopes	estrutura_atomica_periodicidade	1	Isótopos	A=Z+N	Distingue nuclídeos do mesmo elemento por número de nêutrons.	isotopo;nuclideo;neutrons	IUPAC
average_atomic_mass	estrutura_atomica_periodicidade	2	Massa atômica média	A_r=Σ f_i m_i	Calcula média ponderada das massas isotópicas por abundância.	massa atomica;abundancia isotopica;media ponderada	PUBCHEM
electromagnetic_radiation	estrutura_atomica_periodicidade	1	Radiação eletromagnética	c=λν; E=hν	Relaciona frequência, comprimento de onda e energia do fóton.	radiacao eletromagnetica;foton;frequencia	OPENSTAX
photoelectric_quantization	estrutura_atomica_periodicidade	2	Quantização e efeito fotoelétrico	E_foton=hν	Introduz quantização de energia no comportamento eletrônico.	quantizacao;efeito fotoeletrico;planck	MIT_5111
bohr_model	estrutura_atomica_periodicidade	2	Modelo de Bohr para hidrogênio	E_n=-R_Hhc/n^2	Descreve níveis discretos no átomo hidrogenoide como aproximação histórica.	bohr;hidrogenio;niveis de energia	OPENSTAX
de_broglie_chem	estrutura_atomica_periodicidade	3	Dualidade onda-partícula	λ=h/p	Associa comprimento de onda a partículas materiais, base para orbitais.	de broglie;onda de materia;eletron	MIT_561
heisenberg_chem	estrutura_atomica_periodicidade	3	Princípio da incerteza	ΔxΔp≥ħ/2	Limita a definição simultânea de observáveis conjugados.	heisenberg;incerteza;momento	MIT_561
quantum_numbers	estrutura_atomica_periodicidade	2	Números quânticos atômicos	n=1,2...; l=0...n-1; m_l=-l...l; m_s=±1/2	Rotula estados eletrônicos em átomos.	numeros quanticos;orbital;spin	OPENSTAX
atomic_orbitals	estrutura_atomica_periodicidade	2	Orbitais atômicos	|ψ|^2 = densidade de probabilidade	Interpreta orbitais como estados quânticos, não trajetórias clássicas.	orbital atomico;funcao de onda;densidade eletronica	MIT_561
aufbau_pauli_hund	estrutura_atomica_periodicidade	2	Aufbau, Pauli e Hund	ocupação respeita energia, exclusão e multiplicidade	Organiza preenchimento de orbitais em configurações eletrônicas.	aufbau;pauli;hund;configuracao eletronica	OPENSTAX
electron_configuration	estrutura_atomica_periodicidade	1	Configuração eletrônica	Σ ocupações = número de elétrons	Representa distribuição eletrônica em orbitais atômicos.	configuracao eletronica;camadas;subcamadas	PUBCHEM
periodic_table_groups_periods	estrutura_atomica_periodicidade	1	Grupos e períodos da tabela periódica	Z cresce ao longo da tabela	Organiza elementos segundo configuração eletrônica e recorrência de propriedades.	tabela periodica;grupo;periodo	PUBCHEM
effective_nuclear_charge	estrutura_atomica_periodicidade	3	Carga nuclear efetiva	Z_eff≈Z-S	Modela blindagem eletrônica sobre elétrons de valência.	carga nuclear efetiva;blindagem;slater	MIT_5111
atomic_radius_trend	estrutura_atomica_periodicidade	2	Tendência de raio atômico	r depende de n e Z_eff	Explica variação periódica aproximada do tamanho atômico.	raio atomico;tendencia periodica;tamanho atomico	PUBCHEM
ionic_radius	estrutura_atomica_periodicidade	2	Raio iônico	r_cátion<r_átomo; r_ânion>r_átomo em tendências usuais	Relaciona ganho ou perda de elétrons ao tamanho iônico.	raio ionico;cation;anion	PUBCHEM
ionization_energy	estrutura_atomica_periodicidade	2	Energia de ionização	X(g)→X+(g)+e-	Quantifica energia necessária para remover elétron de espécie gasosa.	energia de ionizacao;potencial de ionizacao	NIST_WEBBOOK
electron_affinity	estrutura_atomica_periodicidade	2	Afinidade eletrônica	X(g)+e-→X-(g)	Caracteriza mudança energética associada à captura de elétron.	afinidade eletronica;anion;captura de eletron	NIST_WEBBOOK
electronegativity	estrutura_atomica_periodicidade	2	Eletronegatividade	χ = escala relativa de atração eletrônica	Compara tendência de um átomo atrair densidade eletrônica em ligação.	eletronegatividade;pauling;polaridade	PUBCHEM
periodic_oxidation_states	estrutura_atomica_periodicidade	2	Estados de oxidação periódicos	Σ NOX = carga total	Relaciona valência formal e tendências de grupos periódicos.	estado de oxidacao;nox;valencia	PUBCHEM
diagonal_relationship	estrutura_atomica_periodicidade	3	Relações diagonais na tabela periódica	semelhança≈balanço de raio e densidade de carga	Explica semelhanças químicas entre pares diagonais de elementos leves.	relacao diagonal;litio magnesio;berilio aluminio	MIT_5111
lanthanide_contraction	estrutura_atomica_periodicidade	4	Contração lantanídica	r diminui com Z ao longo dos lantanídeos	Resulta de blindagem imperfeita dos elétrons 4f.	contracao lantanidica;lantanideos;raio ionico	MIT_INORG
relativistic_periodic_effects	estrutura_atomica_periodicidade	5	Efeitos relativísticos em elementos pesados	v_e/c cresce com Z; orbitais s,p1/2 contraem	Explica desvios de tendências periódicas em átomos pesados.	efeito relativistico;ouro;mercurio;elementos pesados	MIT_INORG
isoelectronic_series	estrutura_atomica_periodicidade	2	Séries isoeletrônicas	mesmo N_e; raio tende a cair com Z	Compara espécies com igual número de elétrons sob diferentes cargas nucleares.	serie isoeletronica;raio;eletrons	OPENSTAX
periodicity_machine_readable	estrutura_atomica_periodicidade	3	Propriedades periódicas comparativas	propriedade=f(Z,configuração eletrônica)	Conecta massa, configuração, oxidação, raio, ionização e afinidade em tendências de dados.	propriedades periodicas;tendencias;elementos	PUBCHEM
ionic_bonding	ligacoes_estrutura_molecular	1	Ligação iônica	E_coul∝q1q2/r	Descreve atração eletrostática entre íons em sólidos e pares iônicos.	ligacao ionica;ions;energia reticular	OPENSTAX
covalent_bonding	ligacoes_estrutura_molecular	1	Ligação covalente	ordem de ligação=(N_ligantes-N_antiligantes)/2	Compartilhamento de densidade eletrônica estabiliza átomos em moléculas.	ligacao covalente;compartilhamento;ordem de ligacao	OPENSTAX
metallic_bonding	ligacoes_estrutura_molecular	2	Ligação metálica	coesão depende de elétrons deslocalizados e estrutura de bandas	Explica coesão e propriedades coletivas em metais.	ligacao metalica;metal;eletrons deslocalizados	OPENSTAX
lewis_structures	ligacoes_estrutura_molecular	1	Estruturas de Lewis	elétrons de valência = soma das contribuições ± carga	Representa pares ligantes, pares isolados e conectividade.	lewis;estrutura de lewis;pares de eletrons	OPENSTAX
formal_charge	ligacoes_estrutura_molecular	2	Carga formal	CF=V-N-B/2	Avalia distribuição formal de elétrons em estruturas de Lewis.	carga formal;lewis;ressonancia	OPENSTAX
resonance	ligacoes_estrutura_molecular	2	Ressonância	ψ real ≠ uma única estrutura canônica	Representa deslocalização eletrônica por estruturas-limite equivalentes ou não.	ressonancia;deslocalizacao;estruturas canonicas	IUPAC
octet_rule_limits	ligacoes_estrutura_molecular	2	Regra do octeto e limitações	octeto é heurística, não lei universal	Distingue casos usuais de deficiência, expansão e elétrons desemparelhados.	regra do octeto;octeto expandido;radical	OPENSTAX
vsepr	ligacoes_estrutura_molecular	1	VSEPR	geometria minimiza repulsões entre domínios eletrônicos	Prediz geometrias moleculares a partir de regiões de densidade eletrônica.	vsepr;geometria molecular;repulsao pares eletronicos	OPENSTAX
molecular_geometry	ligacoes_estrutura_molecular	1	Geometria molecular	ângulos dependem de número e tipo de domínios	Relaciona conectividade, pares isolados e forma tridimensional.	geometria molecular;angulo de ligacao;forma molecular	OPENSTAX
bond_polarity	ligacoes_estrutura_molecular	1	Polaridade de ligação	Δχ=|χ_A-χ_B|	Usa diferença de eletronegatividade como indicador qualitativo de polarização.	polaridade;ligacao polar;eletronegatividade	OPENSTAX
molecular_dipole	ligacoes_estrutura_molecular	2	Momento dipolar molecular	μ=Σ q_i r_i	Soma vetorialmente dipolos de ligação e distribuição de carga.	momento dipolar;dipolo;polaridade molecular	NIST_CCCBDB
bond_length_strength	ligacoes_estrutura_molecular	2	Comprimento e energia de ligação	k e D_e tendem a crescer com ordem de ligação	Conecta ordem, comprimento, constante de força e energia de dissociação.	comprimento de ligacao;energia de ligacao;forca de ligacao	NIST_CCCBDB
hybridization	ligacoes_estrutura_molecular	2	Hibridização orbital	sp, sp2, sp3 como modelos de combinação de orbitais	Fornece linguagem de ligação localizada para geometrias comuns.	hibridizacao;sp2;sp3;orbital hibrido	MIT_5111
sigma_pi_bonds	ligacoes_estrutura_molecular	2	Ligações sigma e pi	ligação múltipla = 1σ + π adicionais	Diferencia sobreposição axial e lateral em ligações covalentes.	sigma;pi;ligacao multipla	OPENSTAX
valence_bond_theory	ligacoes_estrutura_molecular	3	Teoria da ligação de valência	Ψ≈combinações de estruturas de ligação localizadas	Modela ligações por sobreposição e acoplamento de orbitais atômicos.	ligacao de valencia;valence bond;sobreposicao	MIT_5111
molecular_orbital_lcao	ligacoes_estrutura_molecular	3	Orbitais moleculares e LCAO	ψ_MO=Σ c_i φ_i	Constrói orbitais moleculares como combinações de orbitais atômicos.	orbital molecular;lcao;mo	MIT_561
bond_order_mo	ligacoes_estrutura_molecular	3	Ordem de ligação em OM	BO=(N_b-N_ab)/2	Relaciona ocupação de orbitais ligantes/antiligantes à estabilidade.	ordem de ligacao;mo;antiligante	MIT_561
homo_lumo	ligacoes_estrutura_molecular	3	HOMO e LUMO	ΔE_HL=E_LUMO-E_HOMO	Conecta orbitais de fronteira a reatividade e excitação eletrônica.	homo;lumo;orbitais de fronteira;gap	NIST_CCCBDB
intermolecular_london	ligacoes_estrutura_molecular	2	Forças de dispersão de London	E_disp≈-C6/r^6	Origina atração de correlações instantâneas de polarização.	london;dispersao;van der waals	IUPAC
dipole_dipole	ligacoes_estrutura_molecular	2	Interações dipolo-dipolo	U∝μ1μ2/r^3 com dependência angular	Descreve interação entre dipolos permanentes.	dipolo dipolo;forca intermolecular	OPENSTAX
hydrogen_bond	ligacoes_estrutura_molecular	2	Ligação de hidrogênio	D-H···A com geometria e energia características	Interação direcional importante em água, biomoléculas e materiais.	ligacao de hidrogenio;ponte de hidrogenio;h bond	IUPAC
ion_dipole	ligacoes_estrutura_molecular	2	Interação íon-dipolo	U∝qμ/r^2 com dependência angular	Ajuda a explicar solvatação de íons em solventes polares.	ion dipolo;solvatacao;hidratacao	OPENSTAX
molecular_symmetry_intro	ligacoes_estrutura_molecular	3	Simetria molecular	operações E,C_n,σ,i,S_n	Classifica moléculas por elementos e operações de simetria.	simetria molecular;grupo pontual;operacao de simetria	MIT_561
group_theory_selection	ligacoes_estrutura_molecular	5	Teoria de grupos e regras de seleção	Γ_produto contém Γ_totalmente_simétrica para integral não nula	Usa representações de simetria para prever atividade espectroscópica.	teoria de grupos;representacao irredutivel;regra de selecao	MIT_561
potential_energy_surface	ligacoes_estrutura_molecular	4	Superfície de energia potencial	E=E(R_1,...,R_N)	Representa energia eletrônica em função da geometria nuclear e conecta estrutura a reação.	superficie de energia potencial;pes;geometria	NIST_CCCBDB
balance_equations	estequiometria_reacoes	1	Balanceamento de equações	A·ν=0 para conservação elemental	Determina coeficientes estequiométricos que conservam átomos e carga.	balanceamento;coeficientes estequiometricos;equacao balanceada	OPENSTAX
stoichiometric_coefficients	estequiometria_reacoes	1	Coeficientes estequiométricos	n_i/|ν_i| relaciona avanço de reação	Conecta quantidades consumidas e formadas pela equação balanceada.	estequiometria;coeficiente estequiometrico;proporcao molar	IUPAC
reaction_extent	estequiometria_reacoes	3	Avanço de reação	dn_i=ν_i dξ	Parametriza progresso reacional com uma única variável extensiva.	avanco de reacao;extensao;xi	IUPAC
mass_to_moles	estequiometria_reacoes	1	Conversão massa–mol	n=m/M	Transforma massas medidas em quantidade de matéria.	massa para mol;mol;massa molar	OPENSTAX
moles_to_particles	estequiometria_reacoes	1	Conversão mol–partículas	N=nN_A	Relaciona quantidade de matéria a número de entidades.	mol para particulas;avogadro;entidades	OPENSTAX
stoich_mass_mass	estequiometria_reacoes	1	Cálculo massa–massa	m_B=m_A(M_B/M_A)(|ν_B|/|ν_A|)	Resolve relações de massa entre reagentes e produtos.	massa massa;estequiometria;calculo estequiometrico	OPENSTAX
limiting_reagent	estequiometria_reacoes	1	Reagente limitante	mínimo de n_i/|ν_i|	Identifica a espécie que esgota primeiro e limita o rendimento teórico.	reagente limitante;excesso;rendimento teorico	OPENSTAX
excess_reagent	estequiometria_reacoes	1	Reagente em excesso	n_restante=n_inicial-|ν|ξ_max	Calcula sobra de reagente após consumo limitado.	reagente em excesso;sobra;estequiometria	OPENSTAX
theoretical_yield	estequiometria_reacoes	1	Rendimento teórico	n_prod,teo=|ν_prod|ξ_max	Determina máximo produto permitido pela estequiometria.	rendimento teorico;produto teorico	OPENSTAX
percent_yield	estequiometria_reacoes	1	Rendimento percentual	%R=100 rendimento_real/rendimento_teórico	Compara produto obtido ao máximo estequiométrico.	rendimento percentual;yield;eficiencia reacao	OPENSTAX
atom_economy	estequiometria_reacoes	2	Economia atômica	EA=100 M_prod_desejado/ΣM_reagentes estequiométricos	Mede incorporação de átomos dos reagentes no produto desejado.	economia atomica;quimica verde;atom economy	IUPAC
combustion_analysis	estequiometria_reacoes	2	Análise por combustão	n_C=n_CO2; n_H=2n_H2O	Infere composição elementar de compostos combustíveis a partir de produtos medidos.	analise combustao;formula empirica;carbono hidrogenio	OPENSTAX
empirical_formula_from_percent	estequiometria_reacoes	2	Fórmula empírica por composição	n_i∝(%m_i)/M_i	Converte percentuais em razões molares inteiras mínimas.	formula empirica;composicao percentual;razao molar	OPENSTAX
solution_stoichiometry	estequiometria_reacoes	2	Estequiometria em solução	n=cV	Combina concentração e volume com coeficientes da reação.	estequiometria em solucao;molaridade;volume	OPENSTAX
gas_stoichiometry	estequiometria_reacoes	2	Estequiometria de gases	n=PV/RT	Liga relações molares da reação a medidas PVT.	estequiometria de gases;gas ideal;volume molar	OPENSTAX
precipitation_reactions	estequiometria_reacoes	1	Reações de precipitação	Q_sp comparado a K_sp	Prevê formação de sólido a partir de íons em solução.	precipitacao;precipitado;ksp	OPENSTAX
acid_base_reaction_stoich	estequiometria_reacoes	1	Estequiometria ácido–base	equivalentes ácido = equivalentes base no ponto estequiométrico	Relaciona transferência de prótons e quantidades equivalentes.	neutralizacao;estequiometria acido base;equivalencia	OPENSTAX
redox_balancing_half_reaction	estequiometria_reacoes	2	Balanceamento redox por semirreações	elétrons perdidos = elétrons ganhos	Balanceia massa e carga separando oxidação e redução.	balanceamento redox;semirreacao;eletrons	OPENSTAX
oxidation_number_method	estequiometria_reacoes	2	Balanceamento por número de oxidação	ΣΔNOX_perdida=ΣΔNOX_ganha	Usa variações de estado de oxidação para ajustar coeficientes.	nox;balanceamento por oxidacao;redox	OPENSTAX
reaction_classification	estequiometria_reacoes	1	Classificação de reações	síntese,decomposição,substituição,metátese,combustão como padrões	Organiza reações por mudanças de conectividade ou transferência.	classificacao de reacoes;sintese;decomposicao	OPENSTAX
net_ionic_equation	estequiometria_reacoes	2	Equação iônica líquida	remove íons espectadores da equação completa	Destaca espécies que sofrem transformação química efetiva.	equacao ionica;ions espectadores;equacao liquida	OPENSTAX
mass_balance_general	estequiometria_reacoes	3	Balanço de massa em sistemas químicos	entrada-saída+geração-consumo=acumulação	Generaliza conservação de espécies e elementos em processos.	balanco de massa;processo quimico;acumulacao	MIT_5111
charge_balance_solution	estequiometria_reacoes	3	Balanço de carga em solução	Σ z_i c_i=0	Impõe eletroneutralidade macroscópica em soluções.	balanco de carga;eletroneutralidade;especiacao	OPENSTAX
element_balance_speciation	estequiometria_reacoes	4	Balanço elementar em especiação	C_T=Σ a_i c_i	Conserva quantidade total de cada componente entre espécies químicas.	balanco elementar;especiacao;concentracao total	MIT_560
reaction_network_stoich_matrix	estequiometria_reacoes	5	Matriz estequiométrica de redes reacionais	dc/dt=N·v(c)	Representa múltiplas reações acopladas em forma matricial.	matriz estequiometrica;rede reacional;stoichiometric matrix	MIT_560
"""
