"""Catálogo modular do STAR WORLD.

As ilhas representam ambientes/capacidades da STAR. Uma ilha pode existir
visualmente no HUB mesmo quando o respectivo pacote de conhecimento ainda
não foi instalado. O campo ``status`` indica o estado do pacote.
"""

ISLANDS = {
    "herois": {
        "name": "Heróis",
        "icon": "🦸",
        "status": "planned",
        "type": "knowledge",
        "description": "Catálogo aprofundado de heróis e personagens, com biografias e referências organizadas.",
        "contents": [
            "biografia, origem e história",
            "evolução do personagem e principais arcos",
            "HQs, edições e cronologias",
            "filmes, séries e outras aparições",
            "família, parentes e relações",
            "poderes, habilidades e equipamentos",
            "versões, universos e identidades",
            "curiosidades e referências",
        ],
    },
    "idiomas": {
        "name": "Idiomas",
        "icon": "🌐",
        "status": "planned",
        "type": "knowledge",
        "description": "Aprendizado de línguas modernas, antigas e históricas, da escrita ao uso prático.",
        "contents": [
            "inglês, espanhol, francês e outras línguas modernas",
            "latim e grego antigo",
            "egípcio antigo e línguas históricas",
            "línguas mesoamericanas e ameríndias",
            "famílias linguísticas e evolução",
            "gramática e vocabulário",
            "pronúncia, escrita e leitura",
            "história, contexto e cultura linguística",
        ],
    },
    "laboratorio": {
        "name": "Laboratório",
        "icon": "🧪",
        "status": "planned",
        "type": "workspace",
        "description": "Ambiente de investigação, ciência, experimentação e análise.",
        "contents": [
            "química e biologia",
            "materiais e propriedades",
            "cálculos e análise científica",
            "hipóteses e testes",
            "experimentos e protocolos",
            "simulações e modelagem",
            "análise de resultados",
        ],
    },
    "central_criacao": {
        "name": "Central de Criação",
        "icon": "🛠️",
        "status": "planned",
        "type": "workspace",
        "description": "Ambiente para construir, desenvolver e testar projetos físicos e tecnológicos.",
        "contents": [
            "máquinas e equipamentos",
            "protótipos e mecanismos",
            "engenharia e mecânica",
            "montagem e fabricação",
            "desenvolvimento físico",
            "testes de protótipos",
        ],
    },
    "biblioteca": {
        "name": "Biblioteca",
        "icon": "📚",
        "status": "planned",
        "type": "knowledge",
        "description": "Grande arquivo de conhecimento armazenado, organizado em livros, documentos e coleções.",
        "contents": [
            "livros e documentos",
            "referências e fontes",
            "coleções de conhecimento",
            "materiais adquiridos",
            "histórico e versões",
            "organização por assunto",
        ],
    },
    "estudio_musica": {
        "name": "Estúdio de Música",
        "icon": "🎵",
        "status": "planned",
        "type": "creative",
        "description": "Espaço dedicado à composição, produção, experimentação e criação musical.",
        "contents": [
            "composição",
            "letras e ideias musicais",
            "beats e produção",
            "experimentação sonora",
            "testes e arranjos",
            "projetos musicais",
        ],
    },
    "observatorio": {
        "name": "Observatório",
        "icon": "🔭",
        "status": "planned",
        "type": "knowledge",
        "description": "Ambiente de astronomia, observação do céu e exploração de corpos celestes.",
        "contents": [
            "estrelas e planetas",
            "corpos celestes",
            "astronomia e astrofísica",
            "exploração astronômica",
            "passagem do tempo e céu noturno",
            "objetos fictícios claramente identificados como ficção",
        ],
    },
    "jardim": {
        "name": "Jardim",
        "icon": "🌱",
        "status": "planned",
        "type": "living",
        "description": "Ambiente vivo para natureza, fauna, flora, água, cultivo, contemplação e descanso.",
        "contents": [
            "plantas, árvores e flores",
            "fauna e animais",
            "água e ecossistemas",
            "cultivo e botânica",
            "natureza e observação",
            "lazer, contemplação e descanso",
            "espaço associado à OSHA, o pet da STAR",
        ],
    },
    "casa": {
        "name": "Casa",
        "icon": "🏠",
        "status": "available",
        "type": "home",
        "description": "A STAR House é o primeiro ambiente 3D navegável do STAR WORLD.",
        "contents": [
            "🛋️ Sala — ambiente navegável com TV interativa",
            "🍳 Cozinha — ambiente navegável; objetos ainda são cenário",
            "🚿 Banheiro — ambiente navegável; objetos ainda são cenário",
            "🛏️ Quarto — TV compartilhada, PC futuro e roupeiro de skins",
            "🌌 Varanda e circulação — conectadas ao mesmo céu global do HUB",
        ],
        "subareas": {
            "sala": {
                "name": "Sala",
                "icon": "🛋️",
                "status": "available",
                "description": "Sala principal da STAR House.",
                "contents": ["TV interativa", "sofá", "rack", "controles", "decoração geek"],
            },
            "cozinha": {
                "name": "Cozinha",
                "icon": "🍳",
                "status": "available",
                "interaction_status": "scenery",
                "description": "Cozinha navegável da STAR House; culinária interativa ainda não foi liberada.",
                "contents": ["bancada", "cooktop", "geladeira", "forno", "pia", "utensílios"],
            },
            "banheiro": {
                "name": "Banheiro",
                "icon": "🚿",
                "status": "available",
                "interaction_status": "scenery",
                "description": "Banheiro navegável da STAR House.",
                "contents": ["bancada", "espelho", "box", "armazenamento"],
            },
            "quarto": {
                "name": "Quarto",
                "icon": "🛏️",
                "status": "available",
                "description": "Espaço pessoal da STAR; o roupeiro concentra a personalização visual.",
                "contents": [
                    "TV interativa compartilhando o mesmo sistema da sala",
                    "PC físico preparado para interação futura",
                    "prateleiras geek decorativas",
                    "roupeiro com seletor de skins",
                ],
            },
        },
    },
    "correio": {
        "name": "Correio",
        "icon": "📬",
        "status": "planned",
        "type": "system",
        "description": "Entrada de encomendas, objetos e acontecimentos narrativos no STAR WORLD.",
        "contents": [
            "recebimento de encomendas",
            "objetos e itens",
            "inventário",
            "registro em memória",
            "eventos e histórias",
            "integração futura com narrativas como a origem da OSHA",
        ],
    },
    "cura": {
        "name": "Cura",
        "icon": "❤️‍🩹",
        "status": "planned",
        "type": "system",
        "description": "Sistema controlado de diagnóstico, manutenção e autocorreção da própria STAR.",
        "contents": [
            "diagnóstico",
            "identificação do problema",
            "proposta de correção",
            "validação",
            "aplicação controlada",
            "teste após correção",
        ],
        "safety_note": "Não concede liberdade irrestrita para alterar o próprio código; toda alteração deve passar por validação e controle.",
    },
}


def get_islands():
    """Retorna uma cópia segura do catálogo para a interface."""
    return {key: dict(value) for key, value in ISLANDS.items()}
