"""Taxonomia cultural da STAR para religiões, tradições e história da magia.

A taxonomia é descritiva e comparativa. Ela não declara afirmações sobrenaturais
como fatos físicos e não reconstrói conhecimento fechado/restrito de comunidades.
"""
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class CulturalSubject:
    key: str
    label: str
    family: str
    region: str
    access_policy: str = "public-scholarly"


# 100 tradições religiosas/religioso-filosóficas + 25 campos de magia/esoterismo.
# Branches são mantidos quando possuem história/identidade próprias relevantes.
SUBJECTS = (
    CulturalSubject("christianity", "Cristianismo", "christian", "global"),
    CulturalSubject("catholicism", "Catolicismo", "christian", "global"),
    CulturalSubject("eastern_orthodoxy", "Ortodoxia Bizantina", "christian", "Europa/Ásia Ocidental"),
    CulturalSubject("oriental_orthodoxy", "Ortodoxia Oriental", "christian", "África/Ásia Ocidental"),
    CulturalSubject("church_of_east", "Igreja do Oriente", "christian", "Ásia Ocidental/Central"),
    CulturalSubject("anglicanism", "Anglicanismo", "christian", "global"),
    CulturalSubject("lutheranism", "Luteranismo", "christian", "global"),
    CulturalSubject("reformed", "Tradições Reformadas e Presbiterianas", "christian", "global"),
    CulturalSubject("methodism", "Metodismo", "christian", "global"),
    CulturalSubject("baptist", "Tradições Batistas", "christian", "global"),
    CulturalSubject("pentecostal", "Pentecostalismo e Carismatismo", "christian", "global"),
    CulturalSubject("adventism", "Adventismo", "christian", "global"),
    CulturalSubject("anabaptism", "Anabatismo, Menonitas e Amish", "christian", "Europa/Américas"),
    CulturalSubject("quakerism", "Quakerismo", "christian", "global"),
    CulturalSubject("latter_day_saint", "Movimento dos Santos dos Últimos Dias", "christian", "global"),
    CulturalSubject("jehovahs_witnesses", "Testemunhas de Jeová", "christian", "global"),
    CulturalSubject("judaism", "Judaísmo", "jewish", "global"),
    CulturalSubject("orthodox_judaism", "Judaísmo Ortodoxo", "jewish", "global"),
    CulturalSubject("conservative_judaism", "Judaísmo Conservador/Masorti", "jewish", "global"),
    CulturalSubject("reform_judaism", "Judaísmo Reformista", "jewish", "global"),
    CulturalSubject("karaite_judaism", "Judaísmo Caraíta", "jewish", "Ásia Ocidental/Europa"),
    CulturalSubject("samaritanism", "Samaritanismo", "abrahamic", "Levante"),
    CulturalSubject("islam", "Islã", "islamic", "global"),
    CulturalSubject("sunni_islam", "Islã Sunita", "islamic", "global"),
    CulturalSubject("shia_islam", "Islã Xiita", "islamic", "global"),
    CulturalSubject("ibadi_islam", "Islã Ibadita", "islamic", "Península Arábica/Norte da África"),
    CulturalSubject("sufism", "Sufismo", "islamic", "global"),
    CulturalSubject("ahmadiyya", "Ahmadiyya", "islamic", "global"),
    CulturalSubject("druze", "Druzos", "west_asian", "Levante"),
    CulturalSubject("bahai", "Fé Bahá'í", "abrahamic", "global"),
    CulturalSubject("mandaeism", "Mandeísmo", "west_asian", "Mesopotâmia/diáspora"),
    CulturalSubject("yazidism", "Yazidismo", "west_asian", "Mesopotâmia/diáspora"),
    CulturalSubject("yarsan", "Yarsan/Ahl-e Haqq", "west_asian", "Irã/Iraque"),
    CulturalSubject("zoroastrianism", "Zoroastrismo", "iranian", "Irã/Índia/diáspora"),
    CulturalSubject("hinduism", "Hinduísmo", "south_asian", "global"),
    CulturalSubject("vaishnavism", "Vaishnavismo", "south_asian", "Sul da Ásia/global"),
    CulturalSubject("shaivism", "Shaivismo", "south_asian", "Sul da Ásia/global"),
    CulturalSubject("shaktism", "Shaktismo", "south_asian", "Sul da Ásia/global"),
    CulturalSubject("smartism", "Smartismo", "south_asian", "Sul da Ásia"),
    CulturalSubject("lingayatism", "Lingayatismo", "south_asian", "Índia"),
    CulturalSubject("sikhism", "Sikhismo", "south_asian", "global"),
    CulturalSubject("jainism", "Jainismo", "south_asian", "global"),
    CulturalSubject("digambara", "Jainismo Digambara", "south_asian", "Índia"),
    CulturalSubject("svetambara", "Jainismo Śvetāmbara", "south_asian", "Índia"),
    CulturalSubject("buddhism", "Budismo", "buddhist", "global"),
    CulturalSubject("theravada", "Budismo Theravāda", "buddhist", "Sul/Sudeste Asiático"),
    CulturalSubject("mahayana", "Budismo Mahāyāna", "buddhist", "Ásia Oriental/global"),
    CulturalSubject("vajrayana", "Budismo Vajrayāna", "buddhist", "Himalaia/Ásia Central"),
    CulturalSubject("zen", "Zen/Chan/Seon/Thiền", "buddhist", "Ásia Oriental/global"),
    CulturalSubject("pure_land", "Budismo Terra Pura", "buddhist", "Ásia Oriental"),
    CulturalSubject("nichiren", "Budismo Nichiren", "buddhist", "Japão/global"),
    CulturalSubject("tibetan_buddhism", "Budismo Tibetano", "buddhist", "Himalaia/global"),
    CulturalSubject("newar_buddhism", "Budismo Newar", "buddhist", "Nepal"),
    CulturalSubject("bon", "Bön", "himalayan", "Tibete/Himalaia"),
    CulturalSubject("confucianism", "Confucionismo", "east_asian", "Ásia Oriental"),
    CulturalSubject("daoism", "Daoismo", "east_asian", "China/global"),
    CulturalSubject("chinese_folk", "Religião popular chinesa", "east_asian", "China/diáspora"),
    CulturalSubject("shinto", "Xintoísmo", "east_asian", "Japão"),
    CulturalSubject("muism", "Muismo/Xamanismo Coreano", "east_asian", "Coreia", "community-sensitive"),
    CulturalSubject("tenrikyo", "Tenrikyō", "east_asian", "Japão/global"),
    CulturalSubject("shugendo", "Shugendō", "east_asian", "Japão", "community-sensitive"),
    CulturalSubject("cao_dai", "Caodaísmo", "southeast_asian", "Vietnã/diáspora"),
    CulturalSubject("dao_mau", "Đạo Mẫu", "southeast_asian", "Vietnã", "community-sensitive"),
    CulturalSubject("kejawen", "Kejawen", "southeast_asian", "Java", "community-sensitive"),
    CulturalSubject("tengrism", "Tengrismo", "central_asian", "Ásia Central"),
    CulturalSubject("mongolian_shamanism", "Xamanismo Mongol", "indigenous", "Mongólia", "community-sensitive"),
    CulturalSubject("siberian_shamanisms", "Tradições xamânicas siberianas", "indigenous", "Sibéria", "community-sensitive"),
    CulturalSubject("ainu_religion", "Religião Ainu", "indigenous", "Japão", "community-sensitive"),
    CulturalSubject("ancient_egyptian", "Religião egípcia antiga", "ancient", "Norte da África"),
    CulturalSubject("mesopotamian", "Religiões mesopotâmicas", "ancient", "Mesopotâmia"),
    CulturalSubject("canaanite", "Religiões cananeias e fenícias", "ancient", "Levante/Mediterrâneo"),
    CulturalSubject("ancient_greek", "Religião grega antiga", "ancient", "Mediterrâneo"),
    CulturalSubject("roman_religion", "Religião romana antiga", "ancient", "Mediterrâneo/Europa"),
    CulturalSubject("norse", "Religião nórdica antiga", "ancient", "Norte da Europa"),
    CulturalSubject("celtic", "Religiões celtas antigas", "ancient", "Europa Ocidental"),
    CulturalSubject("slavic_pagan", "Religiões eslavas pré-cristãs", "ancient", "Europa Oriental"),
    CulturalSubject("baltic_pagan", "Religiões bálticas pré-cristãs", "ancient", "Báltico"),
    CulturalSubject("pre_islamic_arabian", "Religiões árabes pré-islâmicas", "ancient", "Arábia"),
    CulturalSubject("manichaeism", "Maniqueísmo", "historical", "Eurásia"),
    CulturalSubject("gnostic_movements", "Movimentos gnósticos antigos", "historical", "Mediterrâneo/Ásia Ocidental"),
    CulturalSubject("yoruba", "Religião Yorùbá e Ifá", "african", "África Ocidental/diáspora", "community-sensitive"),
    CulturalSubject("vodun", "Vodun", "african", "África Ocidental", "community-sensitive"),
    CulturalSubject("haitian_vodou", "Vodou Haitiano", "afro_diasporic", "Haiti/diáspora", "community-sensitive"),
    CulturalSubject("lukumi", "Lukumí/Santería", "afro_diasporic", "Caribe/diáspora", "community-sensitive"),
    CulturalSubject("candomble", "Candomblé", "afro_diasporic", "Brasil", "community-sensitive"),
    CulturalSubject("umbanda", "Umbanda", "afro_diasporic", "Brasil"),
    CulturalSubject("rastafari", "Rastafari", "afro_diasporic", "Jamaica/global"),
    CulturalSubject("native_american", "Tradições religiosas indígenas da América do Norte", "indigenous", "América do Norte", "community-sensitive"),
    CulturalSubject("dine", "Tradições Diné/Navajo", "indigenous", "América do Norte", "restricted-community-knowledge"),
    CulturalSubject("lakota", "Tradições Lakota", "indigenous", "América do Norte", "restricted-community-knowledge"),
    CulturalSubject("haudenosaunee", "Tradições Haudenosaunee", "indigenous", "América do Norte", "community-sensitive"),
    CulturalSubject("inuit", "Tradições Inuit", "indigenous", "Ártico", "community-sensitive"),
    CulturalSubject("maya", "Religiões Maia", "indigenous", "Mesoamérica", "community-sensitive"),
    CulturalSubject("mexica", "Religião Mexica/Asteca", "indigenous_historical", "Mesoamérica"),
    CulturalSubject("andean", "Tradições religiosas andinas e Inca", "indigenous", "Andes", "community-sensitive"),
    CulturalSubject("mapuche", "Tradição espiritual Mapuche", "indigenous", "Sul da América do Sul", "restricted-community-knowledge"),
    CulturalSubject("guarani", "Tradições Guarani", "indigenous", "América do Sul", "restricted-community-knowledge"),
    CulturalSubject("aboriginal_australian", "Religiões aborígenes australianas", "indigenous", "Austrália", "restricted-community-knowledge"),
    CulturalSubject("maori", "Religião e cosmologia Māori", "indigenous", "Aotearoa/Nova Zelândia", "community-sensitive"),
    CulturalSubject("polynesian", "Tradições religiosas polinésias e havaianas", "indigenous", "Polinésia", "community-sensitive"),

    # História da magia, esoterismo e práticas divinatórias: estudadas como
    # fenômenos históricos/culturais. Não são rotuladas como ciência estabelecida.
    CulturalSubject("western_esotericism", "Esoterismo ocidental", "magic", "Europa/global"),
    CulturalSubject("hermeticism", "Hermetismo", "magic", "Mediterrâneo/Europa"),
    CulturalSubject("ancient_mediterranean_magic", "Magia no Mediterrâneo antigo", "magic", "Mediterrâneo antigo"),
    CulturalSubject("mesopotamian_ritual_magic", "Práticas mágicas e rituais mesopotâmicos", "magic", "Mesopotâmia antiga"),
    CulturalSubject("greco_roman_magic", "Magia greco-romana", "magic", "Mediterrâneo antigo"),
    CulturalSubject("medieval_european_magic", "Magia medieval europeia", "magic", "Europa medieval"),
    CulturalSubject("renaissance_magic", "Magia renascentista", "magic", "Europa renascentista"),
    CulturalSubject("natural_magic", "Magia natural histórica", "magic", "Europa/Mediterâneo"),
    CulturalSubject("grimoire_traditions", "Tradições de grimórios", "magic", "Europa/diásporas"),
    CulturalSubject("ceremonial_magic", "Magia cerimonial", "magic", "Europa/global"),
    CulturalSubject("alchemy", "Alquimia", "magic", "Mediterrâneo/Ásia/Europa"),
    CulturalSubject("astrology", "Astrologia como tradição histórica e divinatória", "magic", "global"),
    CulturalSubject("divination", "Sistemas de adivinhação comparados", "magic", "global"),
    CulturalSubject("talismans_amulets", "Talismãs e amuletos", "magic", "global"),
    CulturalSubject("historical_witchcraft", "Bruxaria histórica e acusações de feitiçaria", "magic", "global"),
    CulturalSubject("folk_magic", "Magia popular e curandeirismo vernacular", "magic", "global", "community-sensitive"),
    CulturalSubject("wicca", "Wicca", "magic", "global"),
    CulturalSubject("thelema", "Thelema", "magic", "global"),
    CulturalSubject("chaos_magic", "Magia do caos", "magic", "global"),
    CulturalSubject("islamic_occult_sciences", "Ciências ocultas no mundo islâmico histórico", "magic", "Ásia Ocidental/Norte da África"),
    CulturalSubject("tantra_mantra_yantra", "Tantra, mantra e yantra em contextos históricos", "magic", "Sul/Ásia Interior", "community-sensitive"),
    CulturalSubject("daoist_ritual_magic", "Rituais, talismãs e práticas esotéricas daoistas", "magic", "China", "community-sensitive"),
    CulturalSubject("onmyodo", "Onmyōdō", "magic", "Japão"),
    CulturalSubject("hoodoo", "Hoodoo e conjure afro-americano", "magic", "Estados Unidos", "community-sensitive"),
    CulturalSubject("obeah", "Obeah", "magic", "Caribe", "community-sensitive"),
)


ASPECTS = (
    "definição e autodescrição",
    "origens e formação histórica",
    "linha do tempo e transformações",
    "geografia e difusão",
    "fontes primárias e cânones",
    "textos e tradições orais",
    "autoridade e interpretação",
    "cosmologia e visão de mundo",
    "divindades, espíritos e seres",
    "antropologia religiosa e natureza humana",
    "doutrinas e conceitos centrais",
    "ética e valores",
    "lei, normas e disciplina",
    "rituais públicos",
    "práticas domésticas e cotidianas",
    "oração, meditação e contemplação",
    "mística e experiência religiosa",
    "iniciação e transmissão",
    "festas e calendários",
    "ritos de passagem",
    "morte, ancestralidade e pós-vida",
    "lugares sagrados e peregrinação",
    "objetos, símbolos e iconografia",
    "arte, arquitetura e materialidade",
    "música, canto e performance",
    "alimentação, jejum e pureza",
    "vestimenta e corpo",
    "família, gênero e papéis sociais",
    "liderança, clero e instituições",
    "comunidades, ordens e movimentos",
    "escolas, ramos e diversidade interna",
    "religião, poder e política",
    "religião, economia e vida social",
    "contato, sincretismo e intercâmbio",
    "conflito, perseguição e tolerância",
    "diáspora, migração e globalização",
    "modernidade, secularização e reforma",
    "ciência, filosofia e epistemologia",
    "demografia e presença contemporânea",
    "fontes, controvérsias e limites do conhecimento",
)

assert len(SUBJECTS) == 125
assert len(ASPECTS) == 40
